apiVersion: apps/v1
kind: Deployment
metadata:
  name: banking-app
  annotations:
    bank.com/build-id: "2025.04.27.001"
    bank.com/owner: "devops-team@bank.com"
    bank.com/version: "v1.2.3"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
      annotations:
        bank.com/deploy-time: "2025-04-27T10:00:00Z"
        bank.com/debug: "enabled"
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80